# Generated by Django 3.0 on 2020-09-28 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OASIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='analysts',
            field=models.ManyToManyField(blank=True, related_name='analyst_endpoint', to=settings.AUTH_USER_MODEL),
        ),
    ]
