# Generated by Django 3.0 on 2020-09-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0002_endpoint_analysts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='alert_level',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='direction',
            field=models.CharField(blank=True, choices=[('consumer', 'Consumer'), ('producer', 'Producer')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
