# Generated by Django 3.0 on 2020-10-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0004_auto_20201002_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='consumer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Consumer', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Producer', to='OASIS.Endpoint'),
        ),
    ]
