# Generated by Django 3.0 on 2020-10-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0005_auto_20201002_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='consumer_id',
            new_name='consumer',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='producer_id',
            new_name='producer',
        ),
    ]
