# Generated by Django 3.0 on 2020-10-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0008_auto_20201007_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprop',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OASIS.Audit'),
        ),
        migrations.AlterField(
            model_name='endpointprop',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Properties', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='intrequestprop',
            name='int_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OASIS.IntRequest'),
        ),
        migrations.AlterField(
            model_name='mftschedule',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumer', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producer', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='routeprop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='OASIS.Route'),
        ),
    ]
