# Generated by Django 3.0 on 2020-12-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0009_auto_20201008_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprop',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditprop', to='OASIS.Audit'),
        ),
        migrations.AlterField(
            model_name='endpointprop',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpointprop', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='endpointprop',
            name='env',
            field=models.CharField(choices=[('DEV', 'DEV'), ('TST', 'TST'), ('PPRD', 'PPRD'), ('PRD', 'PRD'), ('STG', 'STG')], max_length=25),
        ),
        migrations.AlterField(
            model_name='intrequestprop',
            name='int_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrequestprop', to='OASIS.IntRequest'),
        ),
        migrations.AlterField(
            model_name='mftschedule',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mftschedule', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='routeprop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeprop', to='OASIS.Route'),
        ),
    ]
