# Generated by Django 3.0 on 2020-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0010_auto_20201207_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrequestprop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='intrequestprop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
