# Generated by Django 3.0 on 2020-12-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0011_auto_20201207_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditprop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
