# Generated by Django 3.0 on 2020-12-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0013_auto_20201215_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
