# Generated by Django 3.0 on 2020-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0015_auto_20201216_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
