# Generated by Django 3.0 on 2021-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0016_auto_20201217_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftschedule',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mftschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
