# Generated by Django 3.0 on 2021-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0017_auto_20210104_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('import_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
