# Generated by Django 3.0 on 2021-01-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0018_imports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imports',
            new_name='Import',
        ),
    ]
