# Generated by Django 3.0 on 2021-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0019_auto_20210113_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='import_file',
            field=models.FileField(upload_to='import_files'),
        ),
    ]
