# Generated by Django 3.0 on 2021-01-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OASIS', '0020_auto_20210113_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumer', to='OASIS.Endpoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producer', to='OASIS.Endpoint'),
        ),
    ]
